CREATE OR REPLACE TRIGGER TRG_TESTE_DDL_SEQUENCE
BEFORE INSERT ON T_TESTE_DDL_SEQUENCE
FOR EACH ROW
BEGIN
    :NEW.CD_TESTE_SQ := SQ_TESTE_DDL_SEQUENCE.NEXTVAL;
END;
/

DESC T_TESTE_DDL_SEQUENCE;

INSERT INTO T_TESTE_DDL_SEQUENCE (NM_TESTE_SQ)
VALUES ('TESTE TRIGGER');

SELECT * FROM T_TESTE_DDL_SEQUENCE;