SELECT * FROM T_SIP_FUNCIONARIO;

SELECT  T_SIP_FUNCIONARIO.CD_FUNC,
        T_SIP_FUNCIONARIO.NM_FUNCIONARIO,
        T_SIP_FUNCIONARIO.DT_NASCIMENTO,
        T_SIP_FUNCIONARIO.CD_DEPTO
FROM T_SIP_FUNCIONARIO;

SELECT  CD_FUNC,
        NM_FUNCIONARIO,
        DT_NASCIMENTO,
        CD_DEPTO
FROM T_SIP_FUNCIONARIO;

SELECT  F.CD_FUNC,
        F.NM_FUNCIONARIO,
        F.DT_NASCIMENTO,
        F.CD_DEPTO
FROM T_SIP_FUNCIONARIO F;

SELECT  F.CD_FUNC,
        F.NM_FUNCIONARIO,
        F.VL_SALARIO,
        F.CD_DEPTO
FROM T_SIP_FUNCIONARIO F
WHERE F.CD_DEPTO = 6;

SELECT DISTINCT F.CD_DEPTO
FROM T_SIP_FUNCIONARIO F;

SELECT UNIQUE F.CD_DEPTO
FROM T_SIP_FUNCIONARIO F;

SELECT  F.CD_FUNC,
        F.NM_FUNCIONARIO,
        F.VL_SALARIO,
        F.VL_SALARIO * 1.05
FROM T_SIP_FUNCIONARIO F;

SELECT  F.CD_FUNC,
        F.NM_FUNCIONARIO,
        F.VL_SALARIO,
        (F.VL_SALARIO * 12) + 1000 VL_SALARIO_ANUAL
FROM T_SIP_FUNCIONARIO F;

SELECT  F.CD_FUNC,
        F.NM_FUNCIONARIO,
        F.VL_SALARIO,
        F.VL_SALARIO * 1.05 "VALOR AJUSTADO"
FROM T_SIP_FUNCIONARIO F;

SELECT  D.CD_DEPTO,
        D.NM_DEPTO
FROM T_SIP_DEPTO D
ORDER BY D.NM_DEPTO;

SELECT  D.CD_DEPTO,
        D.NM_DEPTO
FROM T_SIP_DEPTO D
ORDER BY D.CD_DEPTO;

SELECT  D.CD_DEPTO,
        D.NM_DEPTO
FROM T_SIP_DEPTO D
ORDER BY D.CD_DEPTO DESC;

SELECT  F.NM_FUNCIONARIO,
        F.VL_SALARIO
FROM T_SIP_FUNCIONARIO F
ORDER BY F.VL_SALARIO DESC;

SELECT  F.CD_FUNC,
        F.NM_FUNCIONARIO,
        F.VL_SALARIO,
        F.CD_DEPTO
FROM T_SIP_FUNCIONARIO F
WHERE F.CD_DEPTO > 1
ORDER BY 4 ASC, 2 DESC;

SELECT  F.CD_FUNC Matrícula,
        F.NM_FUNCIONARIO Nome_Funcionário,
        F.VL_SALARIO "Salário Bruto",
        F.CD_DEPTO Código_Departamento
FROM T_SIP_FUNCIONARIO F;

SELECT  F.CD_FUNC Matrícula,
        F.NM_FUNCIONARIO Nome_Funcionário,
        F.VL_SALARIO "Salário Bruto",
        F.CD_DEPTO Código_Departamento
FROM T_SIP_FUNCIONARIO F
WHERE F.VL_SALARIO > 2999.99;

SELECT  F.CD_FUNC Matrícula,
        F.NM_FUNCIONARIO Nome_Funcionário,
        F.VL_SALARIO "Salário Bruto",
        F.CD_DEPTO Código_Departamento
FROM T_SIP_FUNCIONARIO F
WHERE F.NM_FUNCIONARIO = 'Solange Amoedo Frois';

SELECT  *
FROM    T_SIP_FUNCIONARIO F
WHERE   F.DT_ADMISSAO >= TO_DATE('01/01/2018','DD/MM/YYYY');

SELECT  F.CD_FUNC,
        F.NM_FUNCIONARIO,
        F.CD_DEPTO,
        F.DT_ADMISSAO
FROM    T_SIP_FUNCIONARIO F
WHERE   F.DT_ADMISSAO >= TO_DATE('01/01/2012','DD/MM/YYYY')
AND     F.CD_DEPTO > 3;

SELECT  F.CD_FUNC,
        F.NM_FUNCIONARIO,
        F.CD_DEPTO,
        F.DT_ADMISSAO
FROM    T_SIP_FUNCIONARIO F
WHERE   F.DT_ADMISSAO >= TO_DATE('01/01/2012','DD/MM/YYYY')
AND     1=2;

SELECT  F.CD_FUNC,
        F.NM_FUNCIONARIO,
        F.CD_DEPTO,
        F.DT_ADMISSAO
FROM    T_SIP_FUNCIONARIO F
WHERE   F.DT_ADMISSAO >= TO_DATE('01/01/2018','DD/MM/YYYY')
OR      F.CD_DEPTO = 7;

SELECT  F.CD_FUNC,
        F.NM_FUNCIONARIO,
        F.CD_DEPTO,
        F.DT_ADMISSAO
FROM    T_SIP_FUNCIONARIO F
WHERE   F.DT_ADMISSAO >= TO_DATE('01/01/2018','DD/MM/YYYY')
AND     F.CD_DEPTO = 7;

SELECT  F.CD_FUNC,
        F.NM_FUNCIONARIO,
        F.CD_DEPTO,
        F.DT_ADMISSAO,
        F.VL_SALARIO
FROM    T_SIP_FUNCIONARIO F
WHERE NOT F.CD_DEPTO = 10;

SELECT  F.CD_FUNC,
        F.NM_FUNCIONARIO,
        F.CD_DEPTO,
        F.DT_ADMISSAO,
        F.VL_SALARIO
FROM    T_SIP_FUNCIONARIO F
WHERE   F.DT_ADMISSAO BETWEEN TO_DATE('01/01/2021','DD/MM/YYYY')
AND TO_DATE ('31/12/2021','DD/MM/YYYY');

SELECT  F.CD_FUNC,
        F.NM_FUNCIONARIO,
        F.CD_DEPTO,
        F.DT_ADMISSAO,
        F.VL_SALARIO
FROM    T_SIP_FUNCIONARIO F
WHERE   F.CD_DEPTO IN (1, 7, 4);

SELECT  F.CD_FUNC,
        F.NM_FUNCIONARIO,
        F.CD_DEPTO,
        F.DT_ADMISSAO,
        F.VL_SALARIO
FROM    T_SIP_FUNCIONARIO F
WHERE   TO_CHAR(F.DT_ADMISSAO,'YYYY') IN ('2015', '2018', '2021');

SELECT  F.CD_FUNC,
        F.NM_FUNCIONARIO,
        F.CD_DEPTO,
        F.DT_ADMISSAO,
        F.VL_SALARIO
FROM    T_SIP_FUNCIONARIO F
WHERE   F.CD_DEPTO NOT IN (1, 7, 4);